//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.openschema;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sf.openschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends net.sf.jfuf.fd.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(17, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static net.sf.jfuf.fd.impl.runtime.GrammarInfo grammarInfo = new net.sf.jfuf.fd.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (net.sf.openschema.ObjectFactory.class));
    public final static java.lang.Class version = (net.sf.openschema.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((net.sf.openschema.OpenSchemaType.PredicateType.class), "net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.NodeType.class), "net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl");
        defaultImplementations.put((net.sf.openschema.OpenSchemaType.PredicateType.OutputType.class), "net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.OutputTypeImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.class), "net.sf.openschema.impl.SchemaNodeImpl");
        defaultImplementations.put((net.sf.openschema.OpenSchema.class), "net.sf.openschema.impl.OpenSchemaImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType.class), "net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.AggrBoundaryTypeImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.NodeType.PredicateType.VariableType.class), "net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.PredicateTypeImpl.VariableTypeImpl");
        defaultImplementations.put((net.sf.openschema.OpenSchemaType.PredicateType.VariableType.class), "net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.VariableTypeImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.NodeType.ParBoundaryType.class), "net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.ParBoundaryTypeImpl");
        defaultImplementations.put((net.sf.openschema.SchemaNode.NodeType.PredicateType.class), "net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.PredicateTypeImpl");
        defaultImplementations.put((net.sf.openschema.OpenSchemaType.class), "net.sf.openschema.impl.OpenSchemaTypeImpl");
        defaultImplementations.put((net.sf.openschema.OpenSchemaType.PredicateType.PropertyType.class), "net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.PropertyTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://openschema.sf.net", "OpenSchema"), (net.sf.openschema.OpenSchema.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.openschema
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of OpenSchemaTypePredicateType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchemaType.PredicateType createOpenSchemaTypePredicateType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl();
    }

    /**
     * Create an instance of SchemaNodeNodeType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode.NodeType createSchemaNodeNodeType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl();
    }

    /**
     * Create an instance of OpenSchemaTypePredicateTypeOutputType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchemaType.PredicateType.OutputType createOpenSchemaTypePredicateTypeOutputType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.OutputTypeImpl();
    }

    /**
     * Create an instance of SchemaNode
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode createSchemaNode()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl();
    }

    /**
     * Create an instance of OpenSchema
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchema createOpenSchema()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaImpl();
    }

    /**
     * Create an instance of SchemaNodeNodeTypeAggrBoundaryType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType createSchemaNodeNodeTypeAggrBoundaryType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.AggrBoundaryTypeImpl();
    }

    /**
     * Create an instance of SchemaNodeNodeTypePredicateTypeVariableType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode.NodeType.PredicateType.VariableType createSchemaNodeNodeTypePredicateTypeVariableType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.PredicateTypeImpl.VariableTypeImpl();
    }

    /**
     * Create an instance of OpenSchemaTypePredicateTypeVariableType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchemaType.PredicateType.VariableType createOpenSchemaTypePredicateTypeVariableType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.VariableTypeImpl();
    }

    /**
     * Create an instance of SchemaNodeNodeTypeParBoundaryType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode.NodeType.ParBoundaryType createSchemaNodeNodeTypeParBoundaryType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.ParBoundaryTypeImpl();
    }

    /**
     * Create an instance of SchemaNodeNodeTypePredicateType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.SchemaNode.NodeType.PredicateType createSchemaNodeNodeTypePredicateType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.SchemaNodeImpl.NodeTypeImpl.PredicateTypeImpl();
    }

    /**
     * Create an instance of OpenSchemaType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchemaType createOpenSchemaType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaTypeImpl();
    }

    /**
     * Create an instance of OpenSchemaTypePredicateTypePropertyType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.openschema.OpenSchemaType.PredicateType.PropertyType createOpenSchemaTypePredicateTypePropertyType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.openschema.impl.OpenSchemaTypeImpl.PredicateTypeImpl.PropertyTypeImpl();
    }

}
