//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.openschema;


/**
 * The schema itself, as a regular grammar over the predicates.
 * 
 * Java content class for SchemaNode complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 53)
 * <p>
 * <pre>
 * &lt;complexType name="SchemaNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Node" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Predicate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Variable" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                                     &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ParBoundary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AggrBoundary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Choice" type="{http://openschema.sf.net}SchemaNode"/>
 *                   &lt;element name="Optional" type="{http://openschema.sf.net}SchemaNode"/>
 *                   &lt;element name="Sequence" type="{http://openschema.sf.net}SchemaNode"/>
 *                   &lt;element name="KleeneStar" type="{http://openschema.sf.net}SchemaNode"/>
 *                   &lt;element name="KleenePlus" type="{http://openschema.sf.net}SchemaNode"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SchemaNode {


    /**
     * Gets the value of the Node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link net.sf.openschema.SchemaNode.NodeType}
     * 
     */
    java.util.List getNode();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 59)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Predicate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Variable" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ParBoundary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggrBoundary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Choice" type="{http://openschema.sf.net}SchemaNode"/>
     *         &lt;element name="Optional" type="{http://openschema.sf.net}SchemaNode"/>
     *         &lt;element name="Sequence" type="{http://openschema.sf.net}SchemaNode"/>
     *         &lt;element name="KleeneStar" type="{http://openschema.sf.net}SchemaNode"/>
     *         &lt;element name="KleenePlus" type="{http://openschema.sf.net}SchemaNode"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface NodeType {


        /**
         * Gets the value of the sequence property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        net.sf.openschema.SchemaNode getSequence();

        /**
         * Sets the value of the sequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        void setSequence(net.sf.openschema.SchemaNode value);

        /**
         * Gets the value of the kleenePlus property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        net.sf.openschema.SchemaNode getKleenePlus();

        /**
         * Sets the value of the kleenePlus property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        void setKleenePlus(net.sf.openschema.SchemaNode value);

        /**
         * Gets the value of the predicate property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.PredicateType}
         */
        net.sf.openschema.SchemaNode.NodeType.PredicateType getPredicate();

        /**
         * Sets the value of the predicate property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.PredicateType}
         */
        void setPredicate(net.sf.openschema.SchemaNode.NodeType.PredicateType value);

        /**
         * Gets the value of the parBoundary property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.ParBoundaryType}
         */
        net.sf.openschema.SchemaNode.NodeType.ParBoundaryType getParBoundary();

        /**
         * Sets the value of the parBoundary property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.ParBoundaryType}
         */
        void setParBoundary(net.sf.openschema.SchemaNode.NodeType.ParBoundaryType value);

        /**
         * Gets the value of the optional property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        net.sf.openschema.SchemaNode getOptional();

        /**
         * Sets the value of the optional property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        void setOptional(net.sf.openschema.SchemaNode value);

        /**
         * Gets the value of the choice property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        net.sf.openschema.SchemaNode getChoice();

        /**
         * Sets the value of the choice property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        void setChoice(net.sf.openschema.SchemaNode value);

        /**
         * Gets the value of the aggrBoundary property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType}
         */
        net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType getAggrBoundary();

        /**
         * Sets the value of the aggrBoundary property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType}
         */
        void setAggrBoundary(net.sf.openschema.SchemaNode.NodeType.AggrBoundaryType value);

        /**
         * Gets the value of the kleeneStar property.
         * 
         * @return
         *     possible object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        net.sf.openschema.SchemaNode getKleeneStar();

        /**
         * Sets the value of the kleeneStar property.
         * 
         * @param value
         *     allowed object is
         *     {@link net.sf.openschema.SchemaNode}
         */
        void setKleeneStar(net.sf.openschema.SchemaNode value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 78)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface AggrBoundaryType {


        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 75)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface ParBoundaryType {


        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 62)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Variable" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface PredicateType {


            /**
             * Gets the value of the Variable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the Variable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVariable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link net.sf.openschema.SchemaNode.NodeType.PredicateType.VariableType}
             * 
             */
            java.util.List getVariable();

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getName();

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setName(java.lang.String value);


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/raid/home/pablo/research/planner/openschema/schema/OpenSchema.xsd line 65)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
             *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface VariableType {


                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getValue();

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setValue(java.lang.String value);

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getName();

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setName(java.lang.String value);

            }

        }

    }

}
