//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.openschema.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.3";

}
