//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.jfuf.fd;


/**
 * 
 * An attribute-value pair.  It can contain a ground value or a
 * hierarchy of other attribute-value pairs. It has to contain a
 * mandatory name.
 * 
 * Java content class for AttributeValuePair complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/pablo/research/planner/openschema/schema/FD.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="AttributeValuePair">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="G" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="V" type="{http://jfuf.sf.net/FD}AttributeValuePair" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="N" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AttributeValuePair {


    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getN();

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setN(java.lang.String value);

    /**
     * Gets the value of the V property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the V property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link net.sf.jfuf.fd.AttributeValuePair}
     * 
     */
    java.util.List getV();

    /**
     * Gets the value of the g property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getG();

    /**
     * Sets the value of the g property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setG(java.lang.String value);

}
