//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.jfuf.fd;


/**
 * 
 * An FD.
 * 
 * Java content class for FD element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/pablo/research/planner/openschema/schema/FD.xsd line 10)
 * <p>
 * <pre>
 * &lt;element name="FD">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="V" type="{http://jfuf.sf.net/FD}AttributeValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface FD
    extends javax.xml.bind.Element, net.sf.jfuf.fd.FDType
{


}
