//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.3-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.09 at 03:49:56 EDT 
//


package net.sf.jfuf.fd;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sf.jfuf.fd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends net.sf.jfuf.fd.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static net.sf.jfuf.fd.impl.runtime.GrammarInfo grammarInfo = new net.sf.jfuf.fd.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (net.sf.jfuf.fd.ObjectFactory.class));
    public final static java.lang.Class version = (net.sf.jfuf.fd.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((net.sf.jfuf.fd.FD.class), "net.sf.jfuf.fd.impl.FDImpl");
        defaultImplementations.put((net.sf.jfuf.fd.AttributeValuePair.class), "net.sf.jfuf.fd.impl.AttributeValuePairImpl");
        defaultImplementations.put((net.sf.jfuf.fd.FDType.class), "net.sf.jfuf.fd.impl.FDTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://jfuf.sf.net/FD", "FD"), (net.sf.jfuf.fd.FD.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.jfuf.fd
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of FD
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.jfuf.fd.FD createFD()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.jfuf.fd.impl.FDImpl();
    }

    /**
     * Create an instance of AttributeValuePair
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.jfuf.fd.AttributeValuePair createAttributeValuePair()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.jfuf.fd.impl.AttributeValuePairImpl();
    }

    /**
     * Create an instance of FDType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public net.sf.jfuf.fd.FDType createFDType()
        throws javax.xml.bind.JAXBException
    {
        return new net.sf.jfuf.fd.impl.FDTypeImpl();
    }

}
